modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/FiguraMC/Figura/issues"
license = "LGPL-2.1"
displayURL = "https://github.com/FiguraMC/Figura"

[[mods]]
modId = "figura"
version = "${version}"
displayName = "Figura - Extura(Forge)"
logoFile="assets/figura/icon.png"
authors = "ConstantDust, Superpowers04, PoolloverNathan - ExtExtura"
credits = "superpowers04, ConstantDust, PoolloverNathan"
description = '''
Extensive customization of the Player model. Extura fork
'''


[modproperties.figura]
assets_version="${assets_version}"

[[dependencies.figura]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.figura]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
